[tool.poetry]
name = "ddlsplit"
version = "0.1.0"
description = ""
authors = ["David Berthel <code@davidberthel.de>"]
readme = "README.md"
repository = "https://github.com/winkelband/ddlsplit/"
keywords = [
    "Database",
    "SQL",
    "Documentation",
]
packages = [
    { include = "ddlsplit", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
ddlsplit = "ddlsplit.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
